# Generated by Django 5.0.6 on 2024-06-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='item_name',
            new_name='item',
        ),
    ]
