# Generated by Django 5.0.6 on 2024-08-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_rename_item_name_stock_item'),
        ('Supplier', '0002_alter_supplier_created_by_alter_supplier_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier'),
        ),
    ]
