# Generated by Django 5.0.6 on 2024-08-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_stock_supplier'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='Stocks',
        ),
    ]
