# Generated by Django 5.0.6 on 2024-08-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_alter_stock_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='man_date',
            new_name='mfg_date',
        ),
    ]
