# Generated by Django 5.0.6 on 2024-08-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_rename_man_date_stock_mfg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='trans_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=6),
        ),
    ]
