# Generated by Django 4.2.7 on 2024-06-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mr_Cash', models.CharField(max_length=100)),
                ('Tel', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=1)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Reg_Date', models.DateField(null=True)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Created_By', to=settings.AUTH_USER_MODEL)),
                ('Updated_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Updated_By', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
