# Generated by Django 4.2.7 on 2024-06-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_data_delete_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_data',
            table='Customers',
        ),
    ]
