# Generated by Django 4.2.7 on 2024-06-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_data_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_data',
            old_name='Mr_Cash',
            new_name='Name',
        ),
    ]
