# Generated by Django 4.2.7 on 2024-06-12 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0004_rename_mr_cash_customer_data_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Data',
            new_name='Customer',
        ),
    ]
