# Generated by Django 4.2.7 on 2024-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_rename_customer_data_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Updated_At',
            field=models.DateTimeField(null=True),
        ),
    ]
