# Generated by Django 5.0.6 on 2024-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
