# Generated by Django 5.0.6 on 2024-06-20 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_customer_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Created_By',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Created_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Updated_By',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Updated_By', to=settings.AUTH_USER_MODEL),
        ),
    ]
