# Generated by Django 5.0.6 on 2024-08-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0002_item_measurement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
            ],
        ),
    ]
