# Generated by Django 5.0.6 on 2024-08-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_Measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurement',
            table='Measurements',
        ),
    ]
