# Generated by Django 5.0.6 on 2024-06-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_category',
            name='Category_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
