# Generated by Django 5.0.6 on 2024-08-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_item_category_category_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item_category',
            table='Category',
        ),
    ]
