# Generated by Django 5.0.6 on 2024-08-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_item_measurement_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Items',
        ),
    ]
