# Generated by Django 5.0.6 on 2024-08-26 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Tel', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Reg_Date', models.DateField(null=True)),
                ('Updated_At', models.DateTimeField(null=True)),
                ('Created_By', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Created_By1', to=settings.AUTH_USER_MODEL)),
                ('Updated_By', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Updated_By1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Suppliers',
            },
        ),
    ]
