# Generated by Django 5.0.6 on 2024-08-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sale',
            table='Sales',
        ),
    ]
